<a href="https://colab.research.google.com/github/TulipAggarwal/Data-Structures-and-Algorithms/blob/main/BasicsOfNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [9]:
#initialising a 1-D array in Numpy
a = np.array ([1,2,3], dtype = 'int16') #we are initialising the data type of array a to be of integer 16
print(a)

[1 2 3]


In [3]:
#initialising a 2-D array in Numpy
b = np.array ([[1,2,3],[4,5,6]]) 
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#getting the dimension of a Numpy array
a.ndim #will tell the dimension of array - a

1

In [6]:
#getting the shape of a Numpy array
a.shape #will tell the shape of array - a

(3,)

In [10]:
#getting type of a Numpy array
a.dtype

dtype('int16')

In [11]:
#getting the size of a Numpy array
a.itemsize #will give the number of bytes of array a 

2

In [12]:
#getting the total number of elements of an array
a.size 

3

In [13]:
#getting the total size of an array 
a.nbytes

6